import { boolean, index, jsonb, pgTable, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const id = () => uuid("id").primaryKey().defaultRandom();
const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
export const merchants = pgTable("merchants", { id: id(), publicId: varchar("public_id", { length: 64 }).notNull().unique(), name: varchar("name", { length: 128 }).notNull(), createdAt: createdAt() });
export const credentialRecords = pgTable("api_keys", { id: id(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), credentialDigest: varchar("key_hash", { length: 256 }).notNull().unique(), active: boolean("active").notNull().default(true), createdAt: createdAt() });
export const webhookEndpoints = pgTable("webhook_endpoints", { id: id(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), url: varchar("url", { length: 2048 }).notNull(), credentialDigest: varchar("secret_hash", { length: 256 }).notNull(), active: boolean("active").notNull().default(true), createdAt: createdAt() });
export const payments = pgTable("payments", { id: id(), publicId: varchar("public_id", { length: 64 }).notNull().unique(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), merchantOrderReference: varchar("merchant_order_reference", { length: 128 }).notNull(), idempotencyKey: varchar("idempotency_key", { length: 128 }).notNull(), status: varchar("status", { length: 32 }).notNull(), fiatAmount: varchar("fiat_amount", { length: 40 }).notNull(), fiatCurrency: varchar("fiat_currency", { length: 3 }).notNull(), createdAt: createdAt(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("payments_merchant_order_unique").on(t.merchantId, t.merchantOrderReference), uniqueIndex("payments_merchant_idempotency_unique").on(t.merchantId, t.idempotencyKey)]);
export const quotes = pgTable("quotes", { id: id(), paymentId: uuid("payment_id").notNull().references(() => payments.id), railId: varchar("rail_id", { length: 32 }).notNull(), amountBaseUnits: varchar("amount_base_units", { length: 80 }).notNull(), rate: varchar("rate", { length: 80 }).notNull(), rateSource: varchar("rate_source", { length: 128 }).notNull(), destination: varchar("destination", { length: 128 }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: createdAt() });
export const paymentTransactions = pgTable("payment_transactions", { id: id(), paymentId: uuid("payment_id").notNull().references(() => payments.id), network: varchar("network", { length: 32 }).notNull(), hash: varchar("hash", { length: 128 }).notNull(), createdAt: createdAt() }, (t) => [uniqueIndex("payment_tx_network_hash_unique").on(t.network, t.hash)]);
export const paymentEvents = pgTable("payment_events", { id: id(), paymentId: uuid("payment_id").notNull().references(() => payments.id), type: varchar("type", { length: 64 }).notNull(), data: jsonb("data").notNull(), createdAt: createdAt() });
export const verificationAttempts = pgTable("verification_attempts", { id: id(), paymentTransactionId: uuid("payment_transaction_id").notNull().references(() => paymentTransactions.id), result: varchar("result", { length: 32 }).notNull(), evidence: jsonb("evidence").notNull(), createdAt: createdAt() });
export const verificationJobs = pgTable("verification_jobs", { id: id(), paymentTransactionId: uuid("payment_transaction_id").notNull().unique().references(() => paymentTransactions.id), attempts: varchar("attempts", { length: 8 }).notNull().default("0"), dueAt: timestamp("due_at", { withTimezone: true }).notNull(), leaseUntil: timestamp("lease_until", { withTimezone: true }), createdAt: createdAt() }, (t) => [index("verification_jobs_due_idx").on(t.dueAt)]);
export const webhookEvents = pgTable("webhook_events", { id: id(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), type: varchar("type", { length: 64 }).notNull(), body: jsonb("body").notNull(), createdAt: createdAt() });
export const webhookDeliveries = pgTable("webhook_deliveries", { id: id(), webhookEventId: uuid("webhook_event_id").notNull().references(() => webhookEvents.id), endpointId: uuid("endpoint_id").notNull().references(() => webhookEndpoints.id), dueAt: timestamp("due_at", { withTimezone: true }).notNull(), leaseUntil: timestamp("lease_until", { withTimezone: true }), attempts: varchar("attempts", { length: 8 }).notNull().default("0"), responseStatus: varchar("response_status", { length: 8 }), responseExcerpt: varchar("response_excerpt", { length: 512 }), createdAt: createdAt() }, (t) => [index("webhook_deliveries_due_idx").on(t.dueAt)]);