import type { DeliveredParcel, DeskState, DispatchOrder, DispatchRecord } from "./types";

export const SAMPLE_DELIVERED_PARCELS: DeliveredParcel[] = [
  {
    id: "package-4",
    label: "Package 4",
    trackingNumber: "GLY60505768036SZ",
    carrier: "International parcel",
    status: "delivered",
    receivedAt: "2026-07-12T08:42:00Z",
    reshipper: "urbanblend789",
    country: "United Kingdom",
    items: [
      { productId: "5-amino-50", name: "5-Amino-1MQ 50mg", quantity: 2, dispatchedQuantity: 1 },
      { productId: "ahk-cu-100", name: "AHK-CU 100mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "ara-290", name: "Ara-290 16mg", quantity: 2, dispatchedQuantity: 1 },
      { productId: "bpc-5", name: "BPC 157 10mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "cagri-5", name: "Cagrilintide 5mg", quantity: 2, dispatchedQuantity: 0 },
      { productId: "cardiogen-20", name: "Cardiogen 20mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "dsip-5", name: "DSIP 5mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "epitalon-10", name: "Epitalon 10mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "frag-5", name: "Fragment 176-191 5mg", quantity: 2, dispatchedQuantity: 2 },
      { productId: "ghk-cu-50", name: "GHK-CU 50mg", quantity: 2, dispatchedQuantity: 0 },
      { productId: "tirz-10", name: "Tirzepatide 10mg", quantity: 4, dispatchedQuantity: 1 },
    ],
  },
  {
    id: "package-3",
    label: "Package 3",
    trackingNumber: "SMEX6061610033",
    carrier: "International parcel",
    status: "delivered",
    receivedAt: "2026-07-11T15:18:00Z",
    reshipper: "urbanblend789",
    country: "United Kingdom",
    items: [
      { productId: "hgh-10", name: "HGH 10IU", quantity: 12, dispatchedQuantity: 12 },
      { productId: "pinealon-20", name: "Pinealon 20mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "retra-10", name: "Retatrutide 10mg", quantity: 2, dispatchedQuantity: 0 },
      { productId: "retra-30", name: "Retatrutide 30mg", quantity: 6, dispatchedQuantity: 1 },
      { productId: "sema-5", name: "Semaglutide 10mg", quantity: 3, dispatchedQuantity: 0 },
    ],
  },
  {
    id: "package-6",
    label: "Package 6",
    trackingNumber: "GLY60505764036SZ",
    carrier: "International parcel",
    status: "delivered",
    receivedAt: "2026-07-10T12:06:00Z",
    reshipper: "urbanblend789",
    country: "United Kingdom",
    items: [
      { productId: "mazdutide-10", name: "Mazdutide 10mg", quantity: 1, dispatchedQuantity: 1 },
      { productId: "melanotan-1", name: "Melanotan I 10mg", quantity: 2, dispatchedQuantity: 2 },
      { productId: "melanotan-2", name: "Melanotan II 10mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "mots-c-10", name: "Mots-C 10mg", quantity: 5, dispatchedQuantity: 1 },
      { productId: "na-semax-10", name: "Na Semax 10mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "retra-20", name: "Retatrutide 20mg", quantity: 5, dispatchedQuantity: 2 },
      { productId: "tesa-20", name: "Tesamorelin 20mg", quantity: 4, dispatchedQuantity: 0 },
      { productId: "ss31-10", name: "SS-31 10mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "tb500-5", name: "TB-500 5mg", quantity: 10, dispatchedQuantity: 2 },
    ],
  },
  {
    id: "package-5",
    label: "Package 5",
    trackingNumber: "GLY60505731136SZ",
    carrier: "International parcel",
    status: "delivered",
    receivedAt: "2026-07-09T10:24:00Z",
    reshipper: "urbanblend789",
    country: "United Kingdom",
    items: [
      { productId: "ghk-cu-100", name: "GHK-CU 100mg", quantity: 3, dispatchedQuantity: 0 },
      { productId: "glow", name: "GLOW (TB4 10mg + BPC 10mg + GHK 50mg)", quantity: 6, dispatchedQuantity: 0 },
      { productId: "klow", name: "KLOW (TB 10mg + BPC 10mg + KPV 10mg + GHK 50mg)", quantity: 6, dispatchedQuantity: 2 },
      { productId: "kpv-10", name: "KPV 10mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "kpv-30", name: "KPV 30mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "livagen-20", name: "Livagen 20mg", quantity: 1, dispatchedQuantity: 0 },
      { productId: "ll37-5", name: "LL-37 5mg", quantity: 1, dispatchedQuantity: 1 },
      { productId: "hcg-2000", name: "HCG 2000 IU 10 vials", quantity: 1, dispatchedQuantity: 0 },
    ],
  },
  {
    id: "package-1",
    label: "Package 1",
    trackingNumber: "SMEX6061610030",
    carrier: "International parcel",
    status: "delivered",
    receivedAt: "2026-07-08T14:30:00Z",
    reshipper: "urbanblend789",
    country: "United Kingdom",
    items: [
      { productId: "bac-water-10", name: "BAC water 10ml", quantity: 3, dispatchedQuantity: 0 },
      { productId: "bac-water-3", name: "BAC water 3ml", quantity: 2, dispatchedQuantity: 2 },
      { productId: "cere-30", name: "Cerebrolysin 30mg 10 vials", quantity: 2, dispatchedQuantity: 0 },
      { productId: "nad-500", name: "NAD+ 500mg", quantity: 5, dispatchedQuantity: 2 },
      { productId: "slup-332-1000", name: "Slup-332 1000mcg", quantity: 1, dispatchedQuantity: 0 },
    ],
  },
];

export const SAMPLE_DISPATCH_ORDERS: DispatchOrder[] = [
  {
    id: "order-1042", code: "GB-1042", memberName: "Alice Morgan",
    telegramUsername: "alice_m", deliveryMethod: "Royal Mail Tracked 24",
    shippingCountry: "United Kingdom", qrState: "not_required",
    items: [{ productId: "sema-5", name: "Semaglutide 5mg", quantity: 2 }],
  },
  {
    id: "order-1043", code: "GB-1043", memberName: "Ben Kumar",
    telegramUsername: "ben_k", deliveryMethod: "InPost Locker",
    shippingCountry: "United Kingdom", qrState: "reminder_needed",
    items: [{ productId: "tirz-10", name: "Tirzepatide 10mg", quantity: 2 }],
  },
  {
    id: "order-1044", code: "GB-1044", memberName: "Cara Ellis",
    telegramUsername: "cara_e", deliveryMethod: "InPost Locker",
    shippingCountry: "United Kingdom", qrState: "uploaded",
    items: [{ productId: "bpc-5", name: "BPC-157 5mg", quantity: 2 }],
  },
  {
    id: "order-1045", code: "GB-1045", memberName: "Diego Rossi",
    telegramUsername: "diego_r", deliveryMethod: "International Tracked",
    shippingCountry: "Italy", qrState: "not_required",
    items: [{ productId: "tb500-5", name: "TB-500 5mg", quantity: 8 }],
  },
  {
    id: "order-1046", code: "GB-1046", memberName: "Erin Walsh",
    telegramUsername: "erin_w", deliveryMethod: "InPost Locker",
    shippingCountry: "United Kingdom", qrState: "reminder_needed",
    items: [{ productId: "bpc-5", name: "BPC-157 5mg", quantity: 12 }],
  },
  {
    id: "order-1047", code: "GB-1047", memberName: "Farah Noor",
    telegramUsername: "farah_n", deliveryMethod: "Royal Mail Tracked 48",
    shippingCountry: "United Kingdom", qrState: "not_required",
    items: [{ productId: "cagri-5", name: "Cagrilintide 5mg", quantity: 1 }],
  },
];

export const SAMPLE_DISPATCH_LOG: DispatchRecord[] = [
  {
    id: "order-1038", code: "GB-1038", memberName: "Grace Hall",
    telegramUsername: "grace_h", deliveryMethod: "Royal Mail Tracked 24",
    shippingCountry: "United Kingdom", qrState: "not_required",
    items: [{ productId: "sema-5", name: "Semaglutide 5mg", quantity: 1 }],
    dispatchedAt: "2026-07-11T16:20:00Z", parcelIds: ["parcel-qsc-07"],
    dispatchPhotos: ["GB-1038-counter.jpg"],
  },
  {
    id: "order-1039", code: "GB-1039", memberName: "Hassan Ali",
    telegramUsername: "hassan_a", deliveryMethod: "InPost Locker",
    shippingCountry: "United Kingdom", qrState: "uploaded",
    items: [{ productId: "tirz-10", name: "Tirzepatide 10mg", quantity: 1 }],
    dispatchedAt: "2026-07-11T16:31:00Z", parcelIds: ["parcel-qsc-07"],
    reminderSentAt: "2026-07-11T11:04:00Z", dispatchPhotos: [],
  },
];

export function createInitialDeskState(): DeskState {
  return {
    stage: "receive",
    view: "desk",
    scopeType: "all",
    scopeId: "",
    parcels: structuredClone(SAMPLE_DELIVERED_PARCELS),
    orders: structuredClone(SAMPLE_DISPATCH_ORDERS),
    selectedParcelIds: [],
    fulfilment: null,
    selectedOrderIds: [],
    log: structuredClone(SAMPLE_DISPATCH_LOG),
  };
}
